package hello.demo.mapper;

import hello.demo.model.Comment;
import hello.demo.model.CommentExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface CommentExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Fri Aug 09 20:41:45 CST 2019
     */
    int incCommentCount(Comment comment);
}